### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by Labham-Jain** [chattarajoy/Shatranj#2]
$ python Chess.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "Chess.py", line 4, in <module>
    from ChessPieces import *
  File "C:\Users\Labham Jain\CODE\Python\atom - PYPro\Shatranj-master\ChessPieces.py", line 241, in <module>
    Pawn('MEDIA\WhitePawn.png', squareCenters[48], 'White'),
  File "C:\Users\Labham Jain\CODE\Python\atom - PYPro\Shatranj-master\ChessPieces.py", line 33, in __init__
    ChessPiece.__init__(self, image, position, team)
  File "C:\Users\Labham Jain\CODE\Python\atom - PYPro\Shatranj-master\ChessPieces.py", line 11, in __init__
    self.image = pygame.transform.scale(self.image, (BoardWidth / 8 - BoardWidth / 21, BoardWidth / 8 - BoardWidth / 21))
TypeError: integer argument expected, got float

**Comment by Chirag-sketch** [comment]
In Line11 of ChessPieces.py, change / to //. This should resolve the issue, I got the same error at first.

**Comment by CreepyGeek** [comment]
me to
